---
- hosts: all
  name: Provision Virtual Machine
  remote_user: root
  become: true
  gather_facts: no
  pre_tasks:
  ## Make sure Python 2 is installed so Ansible can run.
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False

  vars:
    - ansible_os_family: "Debian"
    - ansible_distribution: "Ubuntu"

  roles:
    - common
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.nodejs
    - geerlingguy.redis
    - marshall.vagrant